version: '3'
services:
    database:
        container_name: recipsy_database_container
        restart: unless-stopped
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pgpwdrecipsy
            POSTGRES_DB: recipsy_base
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
            - ./recipsy-database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        ports:
            - "5432:5432"
    api:
        image: 'recipsy-server'
        container_name: recipsy-server-container
        restart: always
        ports:
            - "9191:9191"
        environment:
            PORT: 9191
        depends_on:
            - database

volumes:
    postgres: